using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Machina.Solvers.Errors
{
    /// <summary>
    /// A base class to represent errors generated by solvers. 
    /// </summary>
    public abstract class SolverError
    {
        public string Message { get; internal set; }
        public SolverErrorType ErrorType { get; internal set; }

        public SolverError(string msg)
        {
            Message = msg;
            ErrorType = SolverErrorType.Unknown;
        }

        public override string ToString()
        {
            return Message;
        }
    }

    public enum SolverErrorType
    {
        Unknown,
        JointOutOfRange
    }
}
